version: '3.8'

services:
  nest-app:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql